# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins]

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.zsh-autosuggetions]
git = "https://github.com/zsh-users/zsh-autosuggestions"
apply = ['defer']

[plugins.zsh-completions]
git = "https://github.com/zsh-users/zsh-completions"
apply = ['defer']

[plugins.zsh-syntax-highlighting]
git = "https://github.com/zsh-users/zsh-syntax-highlighting"
apply = ['defer']

[plugins.zsh-shift-select]
git = "https://github.com/jirutka/zsh-shift-select"
apply = ['defer']

[plugins.zsh-bd]
git = "https://github.com/Tarrasch/zsh-bd"
apply = ['defer']

[plugins.completions]
local = '~/.zsh/completion'
apply = ['defer', "fpath"]

[plugins.rupaz]
git = "https://github.com/rupa/z"
