onboarding = false

[ui]
agent_panel_sort = "spaces"

[keys]
prefix = "f4"

focus_pane_left = "alt+left"
focus_pane_down = "alt+down"
focus_pane_up = "alt+up"
focus_pane_right = "alt+right"

previous_tab = "alt+shift+left"
next_tab = "alt+shift+right"

previous_workspace = "ctrl+alt+up"
next_workspace = "ctrl+alt+down"

split_vertical = "prefix+slash"

[ui.toast]
delivery = "herdr"

[[keys.command]]
key = "prefix+i"
type = "shell"
{{ if eq .chezmoi.os "windows" -}}
command = "pwsh -NoLogo -Command \"$env:HERDR_ENV='1'; hdr-init\""
{{ else -}}
command = "env HERDR_ENV=1 zsh -ic 'hdr-init'"
{{ end -}}
description = "init herdr workspace template (main/lazygit/nvim)"

[[keys.command]]
key = "alt+g"
type = "popup"
command = "lazygit"
description = "lazygit (popup)"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+d"
type = "popup"
{{ if eq .chezmoi.os "windows" -}}
command = "pwsh -NoLogo -File \"{{ .chezmoi.homeDir }}/.local/bin/hunk-pick.ps1\""
{{ else -}}
command = "hunk-pick"
{{ end -}}
description = "hunk diff (pick range)"
width = "90%"
height = "90%"
